# Numpy

## 라이브러리 임포트

In [2]:
import numpy as np

np.__version__

'1.25.2'

## 파이썬 리스트와 처리 속도 비교

In [4]:
import random

# random.random()
my_arr = [random.random() for i in range(1000000)]
type(my_arr)

list

In [5]:
# 평균내기
%%timeit
import statistics

statistics.mean(my_arr)

615 ms ± 8.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
arr = np.array(my_arr)
type(arr)

numpy.ndarray

In [10]:
# numpy 평균내기
%%timeit

np.mean(arr)

361 µs ± 8.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 배열 생성

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([-1, -2, -3, -4, -5])
# a = [1, 2, 4, 4]

print(arr)
arr1
# print(a)
# a

[1 2 3 4 5]


array([-1, -2, -3, -4, -5])

In [22]:
# arr = np.array([1, 2, 3, 4, 5])
# 2차원 배열
arr = np.array([[1, 2], [3, 4], [5, 6]])

# print(arr.shape)
# arr.ndim
# arr.dtype
# len(arr)
arr.shape

(3, 2)

## 생성과 초기화

In [25]:
np.full((3, 2), -1)

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

In [26]:
arr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

np.zeros_like(arr)
np.zeros(arr.shape)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [27]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱, 슬라이싱

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:] # 0~끝까지
arr[3:]  # 3~끝까지
arr[-1] # 맨뒤에 있는 것
arr[3:-1] # 3~끝에서 1개 앞까지
# arr[a:b] : a~(b-1)까지
arr[-3:] # 5, 6, 7

array([5, 6, 7])

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr[1, 1]

5

## 불리언 인덱싱

In [37]:
arr = np.array([1, 2, 3, 4, 5])

# True인 것만 뽑아옴
idx = np.array([False, False, True, False, True])
arr[idx]

array([3, 5])

In [38]:
# 3보다 큰 데이터만 읽어오기
arr > 3

array([False, False, False,  True,  True])

In [39]:
arr[arr > 3]

array([4, 5])

## fancy indexing

In [41]:
# 내가 뽑아오고 싶은 자리의 위치 인덱스를 입력 -> 해당 위치인 인덱스 뽑아
arr = np.array([1, 2, 3, 4, 5])
idx = np.array([1, 3])
arr[idx]

array([2, 4])

In [42]:
arr = np.array([1, 2, 3, 4, 5])
idx = np.array([[1, 3], [0, 1]])
arr[idx]

array([[2, 4],
       [1, 2]])

In [44]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = -1
arr

array([-1,  2,  3,  4,  5])

## 배열의 형태 변환

In [46]:
# 데이터 처리, 모델 학습 - 내가 만든 데이터 형태 2, 3차원, 모델이 받는 것이 4차원임
# 내가 가진 data 형태와 모델 input shape이 다른 경우가 많이 있음 -> 모델이 받는대로 바꿔줘야 함
# reshape
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
# 2차원으로 변환
arr.reshape(3, 2)

(6,)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
arr

array([1, 2, 3, 4, 5, 6])

In [48]:
# 쭉 펴기
arr.reshape(-1)
arr.flatten()
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [50]:
arr.reshape(1, 2, 3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [51]:
arr.reshape(1, 2, -1) # -1자리는 알아서 계산해서 넣어달라는 의미

array([[[1, 2, 3],
        [4, 5, 6]]])

In [52]:
arr.reshape(1, -1, 1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [53]:
arr2 = arr.reshape(2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.sum(arr2)

21

In [55]:
np.sum(arr2, axis=0)

array([5, 7, 9])

In [56]:
np.sum(arr2, axis=1)

array([ 6, 15])

In [57]:
np.mean(arr2, axis=0)

array([2.5, 3.5, 4.5])

In [58]:
np.mean(arr2, axis=1)

array([2., 5.])

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6])
# 0번째 축을 1로 만들고 싶음
arr.reshape(-1, 6) # 1차원 데이터가 2차원이 됨(새로운 축이 추가됨)

array([[1, 2, 3, 4, 5, 6]])

In [61]:
# 새로운 축 추가
arr[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [62]:
arr[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
# 파일로 저장
np.savez('my_data.npz', train=arr)

In [66]:
# 읽기
data = np.load('my_data.npz')
data['train']

array([1, 2, 3, 4, 5, 6])